# Generated by Django 3.2.4 on 2024-05-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_contactform_contactformform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFormForm',
            new_name='ContactForm',
        ),
    ]
