# Generated by Django 3.2.4 on 2024-06-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_contactformform_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
