# Generated by Django 3.2.4 on 2024-06-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
